[package]
name = "sqlite-graft"
license = "MIT OR Apache"
homepage = "https://github.com/orbitinghail/graft"
repo = "https://github.com/orbitinghail/graft"
description = "A SQLite extension which uses Graft to replicate to and from object storage."
authors = ["Carl Sverre"]
git_tag_format = "v$VERSION"

[targets]
npm = {}
pip = {}
datasette = {}
sqlite_utils = {}
gem = { module_name = "SqliteGraft" }
