[package]
name = "sqlite-graft"
license = "MIT OR Apache"
homepage = "TODO"
repo = "TODO"
description = "TODO"
authors = ["TODO"]
git_tag_format = "v$VERSION"

[targets]
github_releases = {}

pip = {}
datasette = {}
sqlite_utils = {}

npm = {}

gem = { module_name = "SqliteGraft" }
