// @generated
// This file is @generated by prost-build.
/// A set of LSNs
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LsnSet {
    #[prost(uint64, repeated, tag="1")]
    pub lsns: ::prost::alloc::vec::Vec<u64>,
}
// @@protoc_insertion_point(module)
