// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadPagesRequest {
    #[prost(bytes="bytes", tag="1")]
    pub vid: ::prost::bytes::Bytes,
    #[prost(uint64, tag="2")]
    pub lsn: u64,
    #[prost(bytes="bytes", tag="3")]
    pub graft: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PageAtIdx {
    #[prost(uint32, tag="1")]
    pub pageidx: u32,
    #[prost(bytes="bytes", tag="2")]
    pub data: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadPagesResponse {
    #[prost(message, repeated, tag="1")]
    pub pages: ::prost::alloc::vec::Vec<PageAtIdx>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WritePagesRequest {
    #[prost(bytes="bytes", tag="1")]
    pub vid: ::prost::bytes::Bytes,
    #[prost(message, repeated, tag="2")]
    pub pages: ::prost::alloc::vec::Vec<PageAtIdx>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WritePagesResponse {
    #[prost(message, repeated, tag="1")]
    pub segments: ::prost::alloc::vec::Vec<super::super::common::v1::SegmentInfo>,
}
// @@protoc_insertion_point(module)
