#!/usr/bin/env bash
set -euo pipefail

GIT_ROOT="$(git rev-parse --show-toplevel)"
EXAMPLES_LIB_PATH="${GIT_ROOT}/target/debug/examples"
LIB_PATH="${GIT_ROOT}/target/debug"

# detect platform
UNAME_KERNEL="$(uname -s)"
case "${UNAME_KERNEL}" in
    Linux*) PLATFORM=linux ;;
    Darwin*) PLATFORM=osx ;;
    *)
        echo "Unsupported platform: ${UNAME_KERNEL}"
        exit 1
        ;;
esac

SQLITE_YEAR=${SQLITE_YEAR:-2025}
SQLITE_VERSION=${SQLITE_VERSION:-3490100}
SQLITE_URL="https://www.sqlite.org/${SQLITE_YEAR}/sqlite-tools-${PLATFORM}-x64-${SQLITE_VERSION}.zip"
SQLITE_SRC_URL="https://www.sqlite.org/${SQLITE_YEAR}/sqlite-autoconf-${SQLITE_VERSION}.tar.gz"
SQLITE_DIR="${GIT_ROOT}/target/sqlite-${SQLITE_VERSION}"
SQLITE_BIN="${SQLITE_DIR}/sqlite3"

# install sqlite3 into ${GIT_ROOT}/target/sqlite3/
# if it's not already installed
if [ ! -f "${SQLITE_BIN}" ]; then
    if [ $PLATFORM == "linux" ]; then
        echo "Downloading sqlite3 from ${SQLITE_URL} into ${SQLITE_DIR}"
        mkdir -p "${SQLITE_DIR}"
        SQLITE_ZIP="$(mktemp -d)/sqlite3.zip"
        curl -L -o "${SQLITE_ZIP}" "${SQLITE_URL}"
        unzip -d "${SQLITE_DIR}" "${SQLITE_ZIP}"
        rm "${SQLITE_ZIP}"

    elif [ $PLATFORM == "osx" ]; then
        echo "Downloading sqlite3 from ${SQLITE_SRC_URL} into ${SQLITE_DIR}"
        mkdir -p "${SQLITE_DIR}"
        SQLITE_TAR="$(mktemp -d)/sqlite3.tar.gz"
        curl -L -o "${SQLITE_TAR}" "${SQLITE_SRC_URL}"
        tar -C "${SQLITE_DIR}" -xzf "${SQLITE_TAR}"
        rm "${SQLITE_TAR}"
        cd "${SQLITE_DIR}/sqlite-autoconf-${SQLITE_VERSION}"
        export CFLAGS="-DSQLITE_ENABLE_DBSTAT_VTAB"
        ./configure \
            --all \
            --with-readline-ldflags="-L/opt/homebrew/opt/readline/lib -lreadline" \
            --with-readline-header="/opt/homebrew/opt/readline/include/readline/readline.h"
        make -j 4
        mv sqlite3 "${SQLITE_DIR}"
    fi
fi

# make sure sqlite can find the vfs
export LD_LIBRARY_PATH=${LIB_PATH}:${EXAMPLES_LIB_PATH}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export DYLD_LIBRARY_PATH=${LIB_PATH}:${EXAMPLES_LIB_PATH}${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}

# exec sqlite3 with all arguments
exec "${SQLITE_BIN}" "$@"
