#!/usr/bin/env bash
set -euo pipefail

USAGE=$(
    cat <<EOF
Usage: $0 [OPTIONS]

Options:
  --temp        Generate and use a temporary data directory.
  --release     Build/run in release mode.
  --trace       Enable trace-level logging (RUST_LOG=trace).
  --gdb         Run sqlite3 under gdb debugger.
EOF
)

GIT_ROOT="$(git rev-parse --show-toplevel)"

TARGET="debug"
BUILD_FLAGS=""

GDB=${GDB:-0}
export RUST_LOG=${RUST_LOG:-warn}

export GRAFT_REMOTE__TYPE='memory'

# parse flags
while [[ $# -gt 0 ]]; do
    case $1 in
        --temp)
            export GRAFT_DATA_DIR="$(mktemp -d)"
            shift
            ;;
        --release)
            TARGET="release"
            BUILD_FLAGS="--release"
            shift
            ;;
        --trace)
            RUST_LOG="trace"
            shift
            ;;
        --gdb)
            GDB=1
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "${USAGE}"
            exit 1
            ;;
    esac
done

cargo build ${BUILD_FLAGS} --features precept/disabled --package graft-sqlite-extension

# Discover the path to the VFS depending on platform
LIB_PATH="${GIT_ROOT}/target/${TARGET}"
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
    LIB_PATH="${LIB_PATH}/graft.dll"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    LIB_PATH="${LIB_PATH}/libgraft.dylib"
else
    LIB_PATH="${LIB_PATH}/libgraft.so"
fi

ARGS=(
    -header
    -table
    -cmd '.log stderr'
    -cmd ".load '${LIB_PATH}'"
    -cmd ".open 'file:default?vfs=graft'"
)

if [ "${GDB}" == 1 ]; then
    GDB_ARGS=(
        --eval-command="set breakpoint pending on"
        --eval-command="break rust_panic"
        -ex run
        --args sqlite3
        "${ARGS[@]}"
    )
    exec rust-gdb "${GDB_ARGS[@]}"
else
    exec just run sqlite bin "${ARGS[@]}"
fi
