#!/usr/bin/env bash
set -euo pipefail

USAGE=$(
    cat <<EOF
Usage: $0 [OPTIONS]

Options:
  --client ID   Specify an ID to identify this client. Default = "default"
  --release     Build/run in release mode.
  --trace       Enable trace-level logging (RUST_LOG=trace).
  --gdb         Run sqlite3 under gdb debugger.
EOF
)

GIT_ROOT="$(git rev-parse --show-toplevel)"

TARGET="debug"
BUILD_FLAGS=""

GDB=${GDB:-0}
export RUST_LOG=${RUST_LOG:-warn}

CLIENT_ID="default"
DATA_ROOT="${GIT_ROOT}/.graft"

# parse flags
while [[ $# -gt 0 ]]; do
    case $1 in
        --client)
            shift
            CLIENT_ID="$1"
            shift
            ;;
        --release)
            TARGET="release"
            BUILD_FLAGS="--release"
            shift
            ;;
        --trace)
            RUST_LOG="trace"
            shift
            ;;
        --gdb)
            export GDB=1
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "${USAGE}"
            exit 1
            ;;
    esac
done

export GRAFT_REMOTE__TYPE="fs"
export GRAFT_REMOTE__ROOT="${DATA_ROOT}/remote"
export GRAFT_DATA_DIR="${DATA_ROOT}/clients/${CLIENT_ID}"

mkdir -p "${GRAFT_REMOTE__ROOT}" "${GRAFT_DATA_DIR}"

cargo build ${BUILD_FLAGS} --features precept/disabled --package graft-sqlite-extension

# Discover the path to the VFS depending on platform
LIB_PATH="${GIT_ROOT}/target/${TARGET}"
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
    LIB_PATH="${LIB_PATH}/graft.dll"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    LIB_PATH="${LIB_PATH}/libgraft.dylib"
else
    LIB_PATH="${LIB_PATH}/libgraft.so"
fi

ARGS=(
    -header
    -table
    -cmd '.log stderr'
    -cmd ".load '${LIB_PATH}'"
    -cmd ".open 'file:default?vfs=graft'"
)

exec just run sqlite bin "${ARGS[@]}"
